### ISSUE TITLE
Profile and speed up sake

### ISSUE THREAD

**Issue by tonyfischetti** [tonyfischetti/sake#19]
Sake should be profiled on a variety of Sakefiles, the bottlenecks should be noted, and the bottlenecks should be optimized. This should wait until Sake hits version 1... "Premature optimization is the root of all evil" -- Donald Knuth

May also wan't to integrate suggestions from the following whitepaper: http://gittup.org/tup/build_system_rules_and_algorithms.pdf

**Comment by kirbyfan64** [comment]
Just been thinking...

I don't think you're ever really going to get max performance from Python. I love Python, but it tends to be slow and memory-hungry. PyPy only helps when the code is loop-ridden, and Nuitka doesn't give big speed boosts. Cython also doesn't really give too much.

**Comment by tonyfischetti** [comment]
Yeah, do you think it ever interferes with anyone's ability to use it, though?

**Comment by kirbyfan64** [comment]
Well...

I tried to see how long it took to "build" musl (a C99 libc). The Sakefile looked like this:

```yaml
"link x":
    dependencies:
        - "*.o"
    output:
        - x
    formula: echo 456
    help: x

"build %x.o":
    dependencies:
        - "src/%x.c"
    output:
        - "%x.o"
    formula: echo 123
    help: x
```

It didn't even build any of the assembler files!

Now, musl consists of about 1300 files.

How long did it take compared to musl's real makefile that [did much more and was much longer take](http://git.musl-libc.org/cgit/musl/tree/Makefile)?

```
ryan@DevPC-LX:~/stuff/musl$ cd x
ryan@DevPC-LX:~/stuff/musl/x$ time sake -r > /dev/null

real	0m6.384s
user	0m6.314s
sys	0m0.066s
ryan@DevPC-LX:~/stuff/musl/x$ cd ..
ryan@DevPC-LX:~/stuff/musl$ time make -n > /dev/null

real	0m0.206s
user	0m0.194s
sys	0m0.012s
ryan@DevPC-LX:~/stuff/musl$ 
```

That's a *big* difference.

As for PyPy and Cython:

PyPy was much faster, at `0.524` seconds, but still over two times slower than GNU make. I didn't get to test Cython.

I was curious and then compared it to a Ninja build file that was about the same as the Sake file...but I was far too lazy to write out every single C source file. :)
