### ISSUE TITLE
Sake screws up when using multiple dependencies

### ISSUE THREAD

**Issue by refi64** [tonyfischetti/sake#20]
I have the following Sakefile:

``` yaml
#!CC=${CC:-clang} -Wall -Wno-unused-function

build test:
  help:
  dependencies:
    - libcmap.a
    - test.c
  output:
    - test
  formula: $CC -g -I. test.c -L. -lcmap -o test

build cmap:
  help:
  build libcmap.a from object files:
    help:
    dependencies:
      - cmap.o
    output:
      - libcmap.a
    formula: ar rcs libcmap.a cmap.o

  build cmap.o:
    help:
    dependencies:
      - cmap.c
      - cmap.h
    output:
      - cmap.o
    formula: $CC -g -c -I. cmap.c -o cmap.o
```

Logically, it should work fine. However, if I modify cmap.h, only cmap.o is built; libcmap.a and test don't get rebuilt like they should. If I don't use meta-targets, the problem persists. If I run `sake visual`, the dependency graph looks correct.
