### ISSUE TITLE
Some way of architecture-dependent configuration (and pattern rules)

### ISSUE THREAD

**Issue by refi64** [tonyfischetti/sake#24]
I'm trying to decide between [Shake](http://shakebuild.com/) and this. Right now, Sake looks better because my project already needs Python. However, there are two things I need:
- Pattern rules

Or something. Right now, I don't want to write stuff like this:

``` yaml
build x.o:
    help: build x.o
    dependencies:
        - x.c
    output:
        - x.o
    formula: clang x.c -c -o x.o
build y.o:
    help: build y.o
    dependencies:
        - y.c
    output:
        - y.o
    formula: clang y.c -c -o y.o
build z.o:
    help: build z.o
    dependencies:
        - z.c
    output:
        - z.o
    formula: clang z.c -c -o z.o
build app:
    help: build app
    dependencies:
        - x.o
        - y.o
        - z.o
    output:
        - app
    formula: clang x.o y.o z.o -o app
```

THIS IS MAINTENANCE HELL! Another way to do it is:

``` yaml
build myapp:
    help: build myapp
    dependencies:
        - x.c
        - y.c
        - z.c
    output:
         - myapp
    formula: for app in x.c y.c z.c; do clang $app -c -o $(printf $app | sed s/\.c/\.o/); done; clang *.o -o myapp
```

That's barely better and takes forever and a day to compile.
- Configuration

This is the issue of writing a code generator; different files are compiled depending on the architecture. Most make-based build systems use includes for this...but Sake doesn't have includes. Of course, I could use shell scripts for things like the C compiler, but I need to be able to set dependencies based on the current architecture.

Any ideas? I'll happily open a PR for anything.
