### ISSUE TITLE
Phony-ish rule with dependencies

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#47]
I have a weird issue. I'm trying to use Sake for a simple kernel I'm writing in Myrddin. I have this rule:

```yaml
run:
    help: help here
    dependencies:
        - build/disk.img
    formula: "$QEMU -hda build/disk.img"
```

The problem: IT NEVER RUNS!!!! Even if I explicitly do `sake run`, it doesn't do anything at all! The only solution is to add a nonexistent output:

```yaml
run:
    help: help here
    dependencies:
        - build/disk.img
    output: [build/__nonexistent]
    formula: "$QEMU -hda build/disk.img"
```

Which feels ugly. I'm not sure if this is a bug or an unfortunate "feature"...but it sucks.

**Comment by tonyfischetti** [comment]
This sounds like a weird problem.
It won't run if the dependency hasn't changed. Did you look at the .shastore? Has the file changed?
Even if it doesn't have an output, it should still run everytime the dependency changes.
What does verbose mode say?
Does it build with sake -F (force)?
Also, if you want a blank output, you could just leave the field blank (instead of putting [build/__nonexistent] in there

**Comment by kirbyfan64** [comment]
Well...

I just want build/disk.img to be built before running the target. It *does* build with sake -F, but not with an empty output field.

It just feels a little irritating.

**Comment by tonyfischetti** [comment]
What did verbose mode say about it, though?

**Comment by tonyfischetti** [comment]
What you're describing definitely shouldn't happen so let me know what's going on with it. Maybe create a full reproducible example?

**Comment by kirbyfan64** [comment]
This is the smallest Sakefile I can conjure that reproduces the problem:

```yaml
a:
    help: a
    dependencies:
        - a.in
    output:
        - a.out
    formula: "cp a.in a.out"

b:
    help: b
    dependencies:
        - a.out
    output: []
    formula: "echo 123"
```

```
ryan@DevPC-LX:~/stuff/sake/tst6$ sake
Running target a
cp a.in a.out
Running target b
echo 123
123
Done
ryan@DevPC-LX:~/stuff/sake/tst6$ sake
Done
ryan@DevPC-LX:~/stuff/sake/tst6$ sake -F b
Running target b
echo 123
123
Done
ryan@DevPC-LX:~/stuff/sake/tst6$ sake b
Done
ryan@DevPC-LX:~/stuff/sake/tst6$ sake -v b
Call to check_integrity issued
Sakefile passes integrity test
Going to construct Graph
Adding 'a'
Adding 'b'
Nodes are built
Building connections
checking node a for dependencies
it has dependencies
checking node b for dependencies
it has dependencies
checking dep a.in
checking dep a.out
Appending a to matches
Checking that graph is directed acyclic
Dependency resolution is possible
About to take shas of files in target 'a'
It has dependencies
  - a.in
It has outputs
  - a.out
About to take shas of files in target 'b'
It has dependencies
  - a.out
It has outputs
checking .shastore version for potential incompatibilities
Checking if target 'a' needs to be run
Target 'a' doesn't need to run
Checking if target 'b' needs to be run
Target 'b' doesn't need to run
About to take shas of files in target 'a'
It has dependencies
  - a.in
It has outputs
  - a.out
About to take shas of files in target 'b'
It has dependencies
  - a.out
It has outputs
Done
ryan@DevPC-LX:~/stuff/sake/tst6$ 
```
