### ISSUE TITLE
Patterns matched to target names rather than dependency files

### ISSUE THREAD

**Issue by khinsen** [tonyfischetti/sake#49]
The Sakefile below illustrates the problem for which I didn't find a solution: I have many different targets that have no dependencies (they download files from a database) and differ only in one parameter. I can't use patterns for this because patterns are matched on dependencies. Would it be possible to match dependency-free targets using the target name instead? I'd then run `sake "download 193L' to run the target `download %pdb` with `%pdb` set to `193L`.

```yaml
#! DOWNLOAD_PDB = wget http://www.rcsb.org/pdb/files/
#! DOWNLOAD_FASTA = wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=

download 193L:
  help: download protein structure 193L from the PDB 
  dependencies:
  output:
    - 193L.pdb
    - 193L.fasta
  formula: >
    ${DOWNLOAD_PDB}193L.pdb;
    ${DOWNLOAD_FASTA}193L -O 193L.fasta;

download 1B0D:
  help: download protein structure 1B0D from the PDB 
  dependencies:
  output:
    - 1B0D.pdb
    - 1B0D.fasta
  formula: >
    ${DOWNLOAD_PDB}1B0D.pdb;
    ${DOWNLOAD_FASTA}1B0D -O 1B0D.fasta;

download 3KYH:
  help: download protein structure 3KYH from the PDB 
  dependencies:
  output:
    - 3KYH.pdb
    - 3KYH.fasta
  formula: >
    ${DOWNLOAD_PDB}3KYH.pdb;
    ${DOWNLOAD_FASTA}3KYH -O 3KYH.fasta;
```

**Comment by tonyfischetti** [comment]
Hi, khinsen. Thanks for the feedback!
I didn't implement patterns myself and it looks like there's a few problems with it that I'll have to address :( Maybe @kirbyfan64 can help with this.

In the mean-time, if I had to solve the problem you mentioned above, I'd either make one target that downloads all the data, or (more likely) use a shell script like this:
```sh
#!/bin/bash
wget http://www.rcsb.org/pdb/files/$1.pdb
wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=$1.fasta
```
And then all the targets formula will depend on the script and all the formulas can look like:
```
./my_script 3KYH
```
or whatever the protein is.

Hope that helps!

**Comment by kirbyfan64** [comment]
Hmmm...

I think the pattern matching syntax might need to be changed. Right now, patterns are expanded based on dependencies. Expanding patterns in names too *would* work...but it'd lead to weird ambiguities and a crappy implementation.

...but Sake is in a bugfix-only mode...

Besides, implicitly expanding patterns in dependencies can lead to spurious bugs.

My new idea is this (ignore the fact that I didn't quote correctly):

```yaml
build %x.o in dir %y:
 dependencies:
  - %x.c
 output:
  - %x.o
 file patterns:
  - x: %.c
 name patterns: y
```

It's more explicit. Using the current syntax would lead to issues like:

```yaml
download %x:
 dependencies:
  - %x.c
```

Is x a name pattern or a file pattern? Or both?

On a side note, I recently discovered an unfortunate hole in patterns where 1 file matched by a pattern needs an extra dependency.

I'm *really* sorry about the trouble the patterns caused and the mess it created.
