### ISSUE TITLE
Sake gets confused by patterns

### ISSUE THREAD

**Issue by khinsen** [tonyfischetti/sake#50]
What I expect the Sakefile below to do is
 1. Run target "download 193L"
 2. Run target "count residues in 193L.fasta"

Here is what happens instead:
```sh
$ sake -r
Would run target: count residues in %pdb.fasta
Would run target: download 193L
```

```sh
$ sake
Running target count residues in %pdb.fasta
grep -v '^>' %pdb.fasta | fold -w1 | sed -e s/A/ala/ -e s/R/arg/ -e s/N/asn/ -e s/D/asp/ -e s/C/cys/ -e s/Q/gln/ -e s/E/glu/ -e s/G/gly/ -e s/H/his/ -e s/I/ile/ -e s/L/leu/ -e s/K/lys/ -e s/M/met/ -e s/F/phe/ -e s/P/pro/ -e s/S/ser/ -e s/T/thr/ -e s/W/trp/ -e s/Y/tyr/ -e s/V/val/ | tr '[:lower:]' '[:upper:]' | sort | uniq -c > %pdb.fasta-counts;
grep: %pdb.fasta: No such file or directory
File '%pdb.fasta' could not be read! Exiting!
```

Sake takes the pattern %pdb as a file name and runs the patterned target first. It works fine if I run "dowload 193L" manually before a plain `sake`.

```yaml
#! DOWNLOAD_PDB = wget http://www.rcsb.org/pdb/files/
#! DOWNLOAD_FASTA = wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=

download 193L:
  help: download protein structure 193L from the PDB 
  dependencies:
  output:
    - 193L.fasta
  formula: >
    ${DOWNLOAD_FASTA}193L -O 193L.fasta;

count residues in %pdb.fasta:
  help: count the residues in the FASTA sequence file
  dependencies:
    - "%pdb.fasta"
  output:
    - "%pdb.fasta-counts"
  formula: >
    grep -v '^>' %pdb.fasta | fold -w1 | sed -e s/A/ala/ -e s/R/arg/ -e s/N/asn/ -e s/D/asp/ -e s/C/cys/ -e s/Q/gln/ -e s/E/glu/ -e s/G/gly/ -e s/H/his/ -e s/I/ile/ -e s/L/leu/ -e s/K/lys/ -e s/M/met/ -e s/F/phe/ -e s/P/pro/ -e s/S/ser/ -e s/T/thr/ -e s/W/trp/ -e s/Y/tyr/ -e s/V/val/ | tr '[:lower:]' '[:upper:]' | sort | uniq -c > %pdb.fasta-counts;
```

**Comment by kirbyfan64** [comment]
ARG! When I opened the PR for patterns, I had this nagging feeling I was missing something. This was it. Patterns are expanded based on existing files. This has two issues I just realized:

- Meta-targets are not expanded
- What you're seeing: patterns depending on an output don't work

I'll look into this more. Seems like every time I fix a mess I make, I create another one in the process!

**Comment by tonyfischetti** [comment]
@kirbyfan64 what's the status of this?

**Comment by tonyfischetti** [comment]
@kirbyfan64 what's the status of this?

**Comment by kirbyfan64** [comment]
Work-in-progress. Unfortunately, I'm probably going to have to rearrange some stuff to make it work.

**Comment by kirbyfan64** [comment]
@khinsen Working on this...but, as an unrelated side note, you don't need to put semicolons at the end of formulas. Also, your command for counting residues is REALLY long; you can split it over multiple lines. For instance:

```yaml
#! DOWNLOAD_PDB = wget http://www.rcsb.org/pdb/files/
#! DOWNLOAD_FASTA = wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=

download 193L:
  help: download protein structure 193L from the PDB 
  dependencies:
  output:
    - 193L.fasta
  formula: >
    ${DOWNLOAD_FASTA}193L -O 193L.fasta

count residues in %pdb.fasta:
  help: count the residues in the FASTA sequence file
  dependencies:
    - "%pdb.fasta"
  output:
    - "%pdb.fasta-counts"
  formula: >
    grep -v '^>' %pdb.fasta |
    fold -w1 |
    sed -e s/A/ala/ -e s/R/arg/ -e s/N/asn/ -e s/D/asp/ -e s/C/cys/ -e s/Q/gln/ -e s/E/glu/ -e s/G/gly/
           -e s/H/his/ -e s/I/ile/ -e s/L/leu/ -e s/K/lys/ -e s/M/met/ -e s/F/phe/ -e s/P/pro/ -e s/S/ser
           -e s/T/thr/ -e s/W/trp/ -e s/Y/tyr/ -e s/V/val/ |
    tr '[:lower:]' '[:upper:]' | sort | uniq -c > %pdb.fasta-counts
```

When you use `>` to begin a formula, all line breaks are removed. If you use a pipe (`|`) instead, the line breaks are preserved.

Just a side note!
