### ISSUE TITLE
Weakness with patterns and odd dependency trees

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#53]
This is an issue I recently encountered in kernel writing with [Myrddin](http://eigenstate.org/myrddin/). Basically, my makefile is defined like so:

```make
build/%.o build/%.use : src/%.myr
    6m -o build/$*.o $<

build/x.o : build/y.use
```

Basically, I need to be able to add custom dependencies to specific patterns. I can't do this in Sake, so I had to write out the targets fully. For 4 source files. Which sucks.

The idea is to support a syntax like this:

```yaml
"build %.o":
    help: smart stuff here
    dependencies:
        - "src/%stem.myr"
    # this is the magic
    dependencies for build/x.o:
        - build/y.use
    output:
        - "build/%stem.o"
        - "build/%stem.use"
    formula: >
        6m -o build/%stem.o src/%stem.myr
```

I find it still highly readable.
