### ISSUE TITLE
[Ask] Simple example fails when I have subdirectory file

### ISSUE THREAD

**Issue by somenxavier** [tonyfischetti/sake#56]
I have this
```
[xan@argonia proves-sake]$ ls -R
.:
a  Sakefile

./a:
a.tex
```

and this Sakefile:
```
prova:
  help: prova de context
  dependencies:
    - a/a.tex
  formula: >
    cd a
    lualatex a.tex
  output:
    - a/a.pdf
```

I get this:
```
[xan@argonia proves-sake]$ sake
Running target prova
cd a lualatex a.tex
File 'a/a.pdf' could not be read! Exiting!
[xan@argonia proves-sake]$
```
