### ISSUE TITLE
Parse error on named pipes?

### ISSUE THREAD

**Issue by justmytwospence** [tonyfischetti/sake#62]
The following target fails for me:

```
test named pipes:
  help: Testing named pipes
  formula: >
    grep -f  <(echo "foo\nbar") <(echo "bar\nbaz") | sort > foo.txt
  output:
    - foo.txt
```

Running the formula in a shell produces the expected output: a file `foo.txt` that contains the word `bar`. Sake chokes with the following error though:

```
Running target test named pipes
grep -f  <(echo "foo\nbar") <(echo "bar\nbaz") | sort > foo.txt
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `grep -f  <(echo "foo\nbar") <(echo "bar\nbaz") | sort > foo.txt'
Command failed to run
```

What could be causing Sake trouble parsing this command?

**Comment by kirbyfan64** [comment]
Is that Bash syntax, or POSIX shell-compliant?

**Comment by justmytwospence** [comment]
Oh interesting. According to this source: http://wiki.bash-hackers.org/syntax/expansion/proc_subst, process substitution is supported by Bash but is not specified by POSIX and is disabled completely in Bash POSIX mode.

**Comment by kirbyfan64** [comment]
@justmytwospence Yup, that's it. Sake runs tasks in the POSIX shell.

Since #58 hasn't been implemented, you could do something like:

```yaml
test named pipes:
  help: Testing named pipes
  formula: >
    bash 'grep -f  <(echo "foo\nbar") <(echo "bar\nbaz") | sort > foo.txt'
  output:
    - foo.txt
```
